<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mekaar extends Model
{
    use HasFactory;

    protected $table = 'trans_mekaar';
    protected $fillable = [
        'tanggaltarik',
        'tanggalops',
        'wilayah',
        'region',
        'area',
        'cabangid',
        'cabang',
        'noa',
        'standarisasi_ao_on_pkm',
        'jumlah_ao',
        'kebutuhan_ao',
        'standarisasi_fao',
        'fao',
        'kebutuhan_fao',
        'standarisasi_sao',
        'sao',
        'kebutuhan_sao',
        'standarisasi_kum',
        'kum',
        'kebutuhan_kum',
        'noc_bln_lalu',
        'growth_noc_bln_lalu',
        'noc',
        'target_eom_noc',
        'target_eoy_noc',
        'pkm',
        'pkm_lt_10',
        'pkm_gt_30',
        'pkm_10_30',
        'noa_s1',
        'noa_wash',
        'noa_home',
        'penyaluran_noa_kumulatif',
        'penyaluran_noa_bulan_ini',
        'penyaluran_noa_s1',
        'penyaluran_noa_wash',
        'penyaluran_noa_home',
        'os_bln_lalu',
        'growth_os_bln_lalu',
        'os_actual',
        'target_eom_os',
        'target_eoy_os',
        'runoff',
        'sisa_minggu_kerja_sd_des_23',
        'kewajiban_drtd_nominal',
        'kewajiban_drtd_noa',
        'os_s1',
        'os_wash',
        'os_home',
        'lending_okt',
        'penyaluran_plafond_kumulatif',
        'rkap_nov',
        'rkap_des',
        'penyaluran_plafond_bulan_ini',
        'penyaluran_plafond_s1',
        'penyaluran_plafond_wash',
        'penyaluran_plafond_home',
        'noa_par_bln_lalu',
        'progres_noa_par_bln_lalu',
        'noa_par',
        'percentage_noa_par',
        'os_par_bln_lalu',
        'progres_os_par_bln_lalu',
        'os_par',
        'percentage_os_par',
        'target_eom_par',
        'target_eoy_par',
        'percentage_rr',
        'noa_npl_bln_lalu',
        'noa_npl',
        'percentage_noa_npl',
        'os_npl_bln_lalu',
        'os_npl',
        'percentage_os_npl',
        'target_eom_npl',
        'target_eoy_npl',
        'os_bucket_1_30',
        'os_bucket_31_60',
        'os_bucket_61_90',
        'os_bucket_91_120',
        'os_bucket_121_180',
        'os_bucket_180',
        'noa_3r_kol1a',
        'noa_3r_kol1b',
        'noa_3r_kol2',
        'noa_3r_kol3',
        'noa_3r_kol4',
        'noa_3r_kol5',
        'cabang_aktif',
        'noc_3000',
        'par_5_percent',
        'score',
        'kelas_unit',
        'senyum',
        'do_bln_ini',
        'uk_dan_pnc_ao',
    ];
}
